### ISSUE TITLE
Support destroying items

### ISSUE THREAD

**Issue by agrubi** [tim-blair/gloomhaven-map-helper#12]
I'm not sure what's the UX for this. Should we have some area on the screen, and moving item to that area destroys it? Should we start supporting right click on an item with actions like 'destroy', 'rotate' (for traps)?

**Comment by tim-blair** [comment]
I was thinking we'd just move them off the map, just like in the physical game, but adding a destroy would be cool. Might be nice since you go through ~20 monsters each time.

**Comment by tim-blair** [comment]
Why would traps need rotate? They look fine to me.

**Comment by agrubi** [comment]
the double traps

**Comment by agrubi** [comment]
I'll toy with a trash can, will see how it looks

**Comment by tim-blair** [comment]
You mean double obstacles? Right, those need rotate. I figured we'd just use singles for now, but that'd be nice.

**Comment by markspeters** [comment]
Can leverage the existing selection and just have global buttons?  That said I agree I don't see a huge issue with moving off the board.

**Comment by agrubi** [comment]
I was thinking it would be useful to autogenerate standee numbers at some point. Destroying monsters would be helpful for that, especially if a regular monster was removed, and then an elite monster of the same type needs to be created

**Comment by tim-blair** [comment]
We can make the gloomhaven Helper app do that and then just copy them since ours doesn't validate anything. We'd have to add intelligence around how many of each are allowed if we do build it, though.

**Comment by agrubi** [comment]
Ok, I've added trash can. Let's see if it's of any use during scenario. We can always take it out.
